FROM node:20-alpine
WORKDIR /app/frontend
COPY ./package.json ./
COPY ./package-lock.json ./
EXPOSE $PORT
RUN npm ci
COPY ./ ./
CMD [ "npm", "start"]

# # Stage 2: Build the Go backend
# FROM golang:1.21 AS backend-build

# WORKDIR /app/backend
# COPY backend/go.mod backend/go.sum ./
# RUN go mod download
# COPY backend ./
# RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
